version: '3.6'

services:
  traefik:
    image: traefik:v2.0
    command: --providers.docker=true --entryPoints.web.address=:80  --providers.docker.swarmMode=true --providers.docker.endpoint="unix:///var/run/docker.sock" --providers.docker.network=hotspotplusgate
    ports:
    - '80:80'
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    networks:
    - hotspotplusgate
  dashboard:
    image: 'parmenides/hotspotplus-dashboard:latest'
    networks:
      - hotspotplusgate
    deploy:
      labels:
        - traefik.http.routers.dashboard.rule=Host(`my.hotspotplus.ir`)
        - traefik.http.services.dashboard.loadbalancer.server.port=80
    expose:
      - 80
  mongodb:
    image: bitnami/mongodb:3.6
    networks:
      - hotspotplusgate
    expose:
      - 27017
    volumes:
      - hsp_mongodb:/bitnami/mongodb
  hotspot:
    image: 'parmenides/hotspotplus-hotspot:latest'
    networks:
      - hotspotplusgate
    deploy:
      labels:
        - traefik.http.routers.hotspot.rule=Host(`wifi.hotspotplus.ir`)
        - traefik.http.services.hotspot.loadbalancer.server.port=80
    expose:
      - 80
  apihotspotplus:
    image: "parmenides/hotspotplus-api:latest"
    environment:
    - BUSINESS_EMAIL_DOMAIN=info@hotspotplus.ir
    - NODE_ENV=production
    - APP_STATUS=production
    - CUSTOM_HOST=0.0.0.0
    - CUSTOM_PORT=3000
    - DEFAULT_ADMIN_PASSWORD=${admin_password}
    - DEFAULT_ADMIN_USERNAME=${admin_username}
    - DEFAULT_ENCRYPTION_KEY=${encryption_key}
    - DROPBOX_APP_KEY=
    - DROPBOX_APP_SECRET=
    - KAFKA_CONNECTION=kafka1:9092
    - LOG_LEVEL=debug
    - MONGO_DB_NAME=hotspotplus
    - MONGO_IP=mongodb
    - PAYMENT_API_KEY=${payment_api_key}
    - PAYPING_APP_CLIENT_ID=${payping_client_id}
    - PAYPING_APP_TOKEN=${payping_app_token}
    - PAYPING_AUTH_RETURN_URL=${payping_app_oauth_return_url}
    - PANEL_ADDRESS=${panel_address}
    - PAYMENT_SUPPORT_EMAIL=support@hotspotplus.ir
    - PAYMENT_SUPPORT_MOBILE=${support_phone}
    - PERSIAN_SMS_COST=19
    - PRIMARY_SHARED_SECRET=${radius_shred_secret}
    - RADIUS_ACC_PORT=1813
    - RADIUS_AUTH_PORT=1812
    - RADIUS_IP=${radius_ip}
    - REDIS_IP=redis
    - REDIS_PORT=6379
    - SECOND_RADIUS_IP=0.0.0.0
    - ENABLE_SENTRY=false
    - SENTRY_URL=https://17aa1cb1a5034c6eabc84bd08bac9ebf@sentry.io/1771654
    - SENTRY_DASHBOARD_RELEASE_TOKEN=
    - SENTRY_DASHBOARD_URL=${sentry_dashboard_url}
    - SENTRY_RELEASE_TOKEN=
    - SERVICE_MAN_PASSWORD=${servic_man_password}
    - SERVICE_MAN_USERNAME=${servic_man_username}
    - SMS_API_KEY=${sms_api_token}
    - SMS_SIGNATURE=${sms_signature}
    - CLICK_HOST=clickhouse
    - CLICK_USER=admin
    - CLICK_PASSWORD=123
    - REPORT_SERVICE_URL=http://logworker:3000
    networks:
    - hotspotplusgate
    expose:
    - '3000'
    volumes:
    - ${project_dir}/logs/api/:/logs
    - ${project_dir}/files:/files
    container_name: apihotspotplus
    deploy:
      replicas: 1
      labels:
      - traefik.http.routers.apihotspotplus.rule=(Host(`my.hotspotplus.ir`) ||Host(`api.hotspotplus.ir`) || Host(`wifi.hotspotplus.ir`) ) && PathPrefix(`/api`,`/explorer`)
      - traefik.http.services.apihotspotplus.loadbalancer.server.port=3000
  logworker:
    image: 'parmenides/hotspotplus-logworker:latest'
    environment:
    - REPORT_TEMPLATES_PAHT=/app/report-templates
    - CLICK_HOST=clickhouse
    - CLICK_USER=admin
    - CLICK_PASSWORD=123
    - LOG_LEVEL=debug
    volumes:
    - ${project_dir}/logs/log-worker/:/logs
    networks:
    - hotspotplusgate
  clickhouse:
    image: yandex/clickhouse-server:19.17.5.18
    hostname: clickhouse
    deploy:
      resources:
        limits:
          memory: 4G
    expose:
    - 9000
    - 9009
    - 8123
    volumes:
    - ${project_dir}/config/clickhouse/clickhouse_config.xml:/etc/clickhouse-server/config.xml
    - ${project_dir}/config/clickhouse/clickhouse_metrika.xml:/etc/clickhouse-server/metrika.xml
    - ${project_dir}/config/clickhouse/users.xml:/etc/clickhouse-server/users.xml
    -  clickhouse:/var/lib/clickhouse
    networks:
    - hotspotplusgate
  redis:
    image: bitnami/redis:4.0.12-debian-9-r11
    volumes:
    - hsp_redis:/bitnami/redis/data
    environment:
    - ALLOW_EMPTY_PASSWORD=yes
    networks:
    - hotspotplusgate
  zookeeper:
    image: 'bitnami/zookeeper:3-ol-7'
    environment:
    - ALLOW_ANONYMOUS_LOGIN=yes
    expose:
    - 2181
    volumes:
    - zookeeper:/bitnami/zookeeper
    networks:
    - hotspotplusgate
  kafka1:
    image: 'bitnami/kafka:2.3.0-debian-9-r96'
    depends_on:
    - zookeeper
    volumes:
    - kafka1:/bitnami/kafka
    environment:
    - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka1:9092
    - KAFKA_DELETE_TOPIC_ENABLE=true
    - KAFKA_LOG_RETENTION_HOURS=72
    - ALLOW_ANONYMOUS_LOGIN=yes
    - ALLOW_PLAINTEXT_LISTENER=yes
    - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
    - KAFKA_ZOOKEEPER_CONNECT_TIMEOUT_MS=60000
    networks:
    - hotspotplusgate
  ksql:
    image: 'confluentinc/cp-ksql-server:5.3.2'
    container_name: ksql
    networks:
    - hotspotplusgate
    environment:
    - KSQL_PRODUCER_INTERCEPTOR_CLASSES=io.confluent.monitoring.clients.interceptor.MonitoringProducerInterceptor
    - KSQL_CONSUMER_INTERCEPTOR_CLASSES=io.confluent.monitoring.clients.interceptor.MonitoringConsumerInterceptor
    - KSQL_BOOTSTRAP_SERVERS=http://kafka1:9092
    - KSQL_KSQL_STREAMS_BOOTSTRAP_SERVERS=http://kafka1:9092
    - KSQL_LISTENERS=http://0.0.0.0:8088
    - KSQL_KSQL_EXTENSION_DIR=/etc/ksql
    - KSQL_KSQL_SERVICE_ID=ksql_service_1
  radius:
    image: 'freeradius/freeradius-server:3.0.19-alpine'
    volumes:
      - ${project_dir}/radius/clients.conf:/etc/raddb/clients.conf
      - ${project_dir}/radius/mods-enabled/rest:/etc/raddb/mods-enabled/rest
      - ${project_dir}/radius/sites-enabled/dynamic-clients:/etc/raddb/sites-enabled/dynamic-clients
      - ${project_dir}/radius/sites-enabled/default:/etc/raddb/sites-enabled/default
    expose:
      - 1812
      - 1813
    ports:
      - "1812:1812/udp"
      - "1813:1813/udp"
    networks:
      - hotspotplusgate


volumes:
  api_files:
    driver: local
  hsp_mongodb:
    driver: local
  hsp_redis:
    driver: local
  kafka1:
    driver: local
  clickhouse:
    driver: local
  zookeeper:
    driver: local

networks:
  hotspotplusgate:
    driver: overlay
    attachable: true